# Generated by Django 4.0.1 on 2022-07-12 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0022_nurse_nurse_user_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('R', 'RECEPTION'), ('N', 'NURSE'), ('D', 'DOCTOR'), ('P', 'PHARMACY'), ('L', 'LAB'), ('A', 'ACCOUNT')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
