# Generated by Django 4.0.1 on 2022-07-12 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_staff_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Room_ID',
            new_name='Room_NUMBER',
        ),
        migrations.RemoveField(
            model_name='alloted_beds',
            name='Alloted_patient',
        ),
        migrations.RemoveField(
            model_name='alloted_beds',
            name='Alloted_time',
        ),
        migrations.RemoveField(
            model_name='alloted_beds',
            name='Bed_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Patient_doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Patient_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Patient_room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Room_availability',
        ),
        migrations.AddField(
            model_name='alloted_beds',
            name='Bed_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alloted_beds',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.room'),
        ),
        migrations.AddField(
            model_name='staff_type',
            name='Profile_image',
            field=models.ImageField(blank=True, default='Null', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='staff_type',
            name='staff_location',
            field=models.CharField(default='tol', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_type',
            name='staff_phone_number',
            field=models.CharField(default='0909', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='Patient_age',
            field=models.IntegerField(default=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='Patient_blood_genotype',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Patient_blood_group',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Patient_email_address',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.AddField(
            model_name='roomlog',
            name='Bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.alloted_beds'),
        ),
        migrations.AddField(
            model_name='roomlog',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.patient'),
        ),
        migrations.AddField(
            model_name='roomlog',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.room'),
        ),
    ]
