# Generated by Django 4.0.1 on 2022-07-13 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_roomlog_rename_room_id_room_room_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment_date',
            new_name='Appointment_start_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Appointment_completed',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Contact_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Contact_phone',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Fullname',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='entered_by',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_status',
            field=models.CharField(choices=[('A', 'active'), ('W', 'waiting'), ('C', 'cancelled'), ('F', 'finished')], default='W', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Assigned_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Doctor_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Other_Staff',
        ),
    ]
