# Generated by Django 4.0.1 on 2022-07-14 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0025_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_type',
            old_name='staff_phone_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='staff_type',
            name='staff_location',
        ),
        migrations.AddField(
            model_name='staff_type',
            name='gender',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_type',
            name='location',
            field=models.CharField(default='wingA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff_type',
            name='specialization',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Assigned_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='birth_report',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
