# Generated by Django 4.0.1 on 2022-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_alter_appointment_appointment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_status',
            field=models.CharField(choices=[('active', 'active'), ('waiting', 'waiting'), ('cancelled', 'cancelled'), ('finished', 'finished')], default='W', max_length=200),
        ),
    ]
