# Generated by Django 4.0.1 on 2022-07-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='patient',
            name='Alergies',
            field=models.TextField(default='fish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_status',
            field=models.CharField(choices=[('active', 'active'), ('waiting', 'waiting'), ('cancelled', 'cancelled'), ('finished', 'finished')], default='waiting', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Reason_for_Appointment',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.CreateModel(
            name='Patient_medical_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('blood_pressure', models.IntegerField(blank=True, null=True)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_prescribed', models.DateField()),
                ('Medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.medicine')),
            ],
        ),
    ]
