# Generated by Django 4.0.1 on 2022-07-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_rename_amount_medicine_price_patient_alergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_log',
            name='frequency',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine_log',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('hourly', 'hourly')], default='daily', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine_log',
            name='more_description',
            field=models.TextField(default='wowzers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine_log',
            name='Date_prescribed',
            field=models.DateField(auto_created=True),
        ),
    ]
