# Generated by Django 4.0.1 on 2022-07-15 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0030_medicine_log_frequency_medicine_log_frequency_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_log',
            name='administerd_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine_log',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.patient'),
            preserve_default=False,
        ),
    ]
