# Generated by Django 4.0.1 on 2022-07-15 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_medicine_log_administerd_by_medicine_log_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_log',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.room'),
        ),
    ]
