# Generated by Django 4.0.1 on 2022-07-16 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_medicine_log_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Patient_age',
        ),
        migrations.AddField(
            model_name='patient',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
