# Generated by Django 4.0.1 on 2022-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_remove_patient_patient_age_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_log',
            name='collected',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
