# Generated by Django 4.0.1 on 2022-07-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_medicine_log_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_medical_log',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
