# Generated by Django 4.0.1 on 2022-07-16 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0035_patient_medical_log_more_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_medical_log',
            name='treated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
