# Generated by Django 4.0.1 on 2022-07-17 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_patient_medical_log_treated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_medical_log',
            name='date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
