# Generated by Django 4.0.1 on 2022-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_patient_medical_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
