# Generated by Django 4.0.1 on 2022-07-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_medicine_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Avaialble_beds',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomlog',
            name='Bed',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Alloted_Beds',
        ),
    ]
